package Main.Engine.Evolution.TimeTableSolution.Classes;

import Main.Engine.Xml.AutoGenerated.ETTClass;
import Main.Engine.Xml.AutoGenerated.ETTStudy;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class Grade implements Serializable {
    private Integer id;
    private String name;
    private Map<Integer, Integer> subjectIdToWeeklyHours;

    public Grade(Integer _id, String _name, Map<Integer, Integer> _subjectIdToWeeklyHours)
    {
        this.id = _id;
        this.name = _name;
        this.subjectIdToWeeklyHours = new HashMap<>(_subjectIdToWeeklyHours);
    }

    public Grade(Grade other)
    {
        this.id = other.id;
        this.name = other.name;
        this.subjectIdToWeeklyHours = new HashMap<>(other.subjectIdToWeeklyHours);
    }

    public Grade(ETTClass ettGrade)
    {
        this.id = ettGrade.getId();
        this.name = ettGrade.getETTName();
        this.subjectIdToWeeklyHours = generateMapFromETT(ettGrade.getETTRequirements().getETTStudy());
    }

    private Map<Integer, Integer> generateMapFromETT(List<ETTStudy> ettListOfSubjectIdToHours)
    {
        Map<Integer, Integer> newMap = new HashMap<>();

        for(ETTStudy idToHours : ettListOfSubjectIdToHours)
            newMap.put(idToHours.getSubjectId(), idToHours.getHours());

        return newMap;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Grade grade = (Grade) o;
        return Objects.equals(id, grade.id) && Objects.equals(name, grade.name) && Objects.equals(subjectIdToWeeklyHours, grade.subjectIdToWeeklyHours);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, subjectIdToWeeklyHours);
    }

    @Override
    public String toString() {
        return "Grade{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subjectIdToWeeklyHours=" + subjectIdToWeeklyHours +
                '}';
    }

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Map<Integer, Integer> getSubjectIdToWeeklyHours() {
        return subjectIdToWeeklyHours;
    }
}
