package Main.Engine.Xml;

import Main.Engine.Xml.AutoGenerated.ETTDescriptor;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;
import java.io.File;

public class XmlReader {
    public static ETTDescriptor createETTDescriptorFromXmlFile(String XMLPath)
    {
        XmlChecker.isLegalFile(XMLPath);

        File xmlFile = new File(XMLPath);
        ETTDescriptor descriptor = null;
        try{
            JAXBContext jaxbContext = JAXBContext.newInstance(ETTDescriptor.class);
            Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
            descriptor = (ETTDescriptor) jaxbUnmarshaller.unmarshal(xmlFile);
        }
        catch(Exception e)
        {
            return null;
        }

        XmlChecker.CheckDescriptor(descriptor);

        return descriptor;
    }
}
